name: add-content
description: Use this template to add new content
title: "Add content"
labels: ["content"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Do not change the title of this issue.

  - type: input
    id: content-title
    attributes:
      label: Title
      description: Provide a brief title for the content
      placeholder: "Enter content title here"

  - type: textarea
    id: content-body
    attributes:
      label: Content
      description: Provide the content you would like to add
      placeholder: "Enter content here"
