name: Issue to post

on:
  issues:
    types: [opened, edited, reopened]

jobs:
  save-issue:
    if: >
      github.event.issue.user.login == 'carrotflakes' &&
      github.event.issue.title == 'Add content'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Create content file
        run: |
          # Create content directory if it doesn't exist
          mkdir -p content/posts/issue
          
          # Use environment variables to safely handle the issue body
          read -r ISSUE_BODY <<'EOFEOFEOF'
          ${{ toJSON(github.event.issue.body) }}
          EOFEOFEOF
          # Extract sections using safer methods
          TITLE=$(echo "$ISSUE_BODY" | jq -r '
            split("\n") |
            .[index("### Title")+1:index("### Content")] |
            map(select(length > 0)) |
            join(" ")
          ')
          CONTENT=$(echo "$ISSUE_BODY" | jq -r '
            split("\n") |
            .[index("### Content")+1:] |
            join("\n")
          ')
          WRITER="${{ github.event.issue.user.login }}"
          
          # Convert title to filename-safe format using safer method
          SAFE_TITLE=$(echo "$TITLE" | tr '[:space:]' '-' | tr -cd '[:alnum:]-' | sed 's/-*$//')

          # Create temporary file with proper escaping
          jq -n \
            --arg date "${{ github.event.issue.created_at }}" \
            --arg title "$TITLE" \
            --arg writer "$WRITER" \
            --arg content "$CONTENT" \
            '{date: $date, title: $title, writer: $writer, content: $content}' > temp.json

          # Create the markdown file using jq for proper escaping
          jq -r '"+++
          date = \(.date)
          title = \(.title|@json)
          draft = false
          writer = \(.writer|@json)
          +++

          \(.content)"' temp.json > "content/posts/issue/${SAFE_TITLE}.md"

          rm temp.json

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add content/posts/issue/
          git commit -m "Add content from issue: #${{ github.event.issue.number }}"
          git push

      - name: Close issue
        run: |
          curl -X PATCH \
            -H "Authorization: token ${{ github.token }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}" \
            -d '{"state":"closed"}'
