name: Issue to post

on:
  issues:
    types: [opened]

jobs:
  save-issue:
    if: github.event.issue.user.login == 'carrotflakes' && github.event.issue.title == 'Add content'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Create content file
        run: |
          # Create content directory if it doesn't exist
          mkdir -p content/issue
          
          # Extract title and content from issue body
          ISSUE_BODY="${{ github.event.issue.body }}"
          TITLE=$(echo "$ISSUE_BODY" | sed -n '/^### Title/,/^#/p' | sed '1d;$d' | xargs)
          CONTENT=$(echo "$ISSUE_BODY" | sed -n '/^### Content/,$p' | sed '1d')
          WRITER="${{ github.event.issue.user.login }}"
          
          # Convert title to filename-safe format and create .md file
          SAFE_TITLE=$(echo "$TITLE" | tr ' ' '-' | tr -cd '[:alnum:]-')

          # Create the markdown file with extracted content
          cat > "content/issue/${SAFE_TITLE}.md" << EOL
          +++
          date = '${{ github.event.issue.created_at }}'
          title = '$TITLE'
          draft = false
          writer = '$WRITER'
          +++

          $CONTENT
          EOL

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add content/issue/
          git commit -m "Add content from issue: ${{ github.event.issue.number }}"
          git push

      - name: Close issue
        run: |
          curl -X PATCH \
            -H "Authorization: token ${{ github.token }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}" \
            -d '{"state":"closed"}'
